/**:
    ros__parameters:
      monitor_configured_only: True
      topics:
        - /driving/hesai/F/pandar
        - /driving/hesai/FL/pandar
        - /driving/velodyne/FR/velodyne_points
        - /driving/velodyne/RL/velodyne_points
        - /driving/velodyne/RR/velodyne_points
        - /driving/lidar/points
      min_values:
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
      max_values:
        - 15.0
        - 15.0
        - 15.0
        - 15.0
        - 15.0
        - 15.0
