/**:
    ros__parameters:
      monitor_configured_only: True
      topics:
        - /driving/hesai/F/pandar
        - /driving/hesai/FL/pandar
        - /driving/velodyne/FR/velodyne_points
        - /driving/velodyne/RL/velodyne_points
        - /driving/velodyne/RR/velodyne_points
        - /driving/lidar/points
      min_values:
        - -0.09
        - -0.09
        - -0.09
        - -0.09
        - -0.09
        - -0.09
      max_values:
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
