/diagnostics/topic_frequency_monitor:
    ros__parameters:
      monitor_configured_only: True
      topics:
        - /driving/hesai/F/pandar
        - /driving/hesai/FL/pandar
        - /driving/velodyne/FR/velodyne_points
        - /driving/velodyne/RL/velodyne_points
        - /driving/velodyne/RR/velodyne_points
        - /driving/lidar/points
      min_freqs:
        - 9.5
        - 9.5
        - 9.5
        - 9.5
        - 9.5
        - 9.5
      max_freqs:
        - 51.0
        - 10.5
        - 100.0
        - 10.5
        - 10.5
        - 10.5

/diagnostics/message_age_monitor:
    ros__parameters:
      monitor_configured_only: True
      topics:
        - /driving/hesai/F/pandar
        - /driving/hesai/FL/pandar
        - /driving/velodyne/FR/velodyne_points
        - /driving/velodyne/RL/velodyne_points
        - /driving/velodyne/RR/velodyne_points
        - /driving/lidar/points
      min_delays:
        - -0.09  # can occur due to simulated time
        - -0.09
        - -0.09
        - 0.0
        - 0.0
      max_delays:
        - 0.1
        - 0.1
        - 0.1
        - 0.200
        - 0.200


